version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${COVID_DB_USER}
      POSTGRES_PASSWORD: ${COVID_DB_PASSWORD}
      POSTGRES_DB: 'covid'
    ports:
      - 5432:5432
    volumes:
      - ${COVID_DB_VOLUME}:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
